// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: helloapp/v1/hello.proto

package gRPCconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Calvados-1997/Calc_RPC/pkg/gRPC/helloapp/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GreetingServiceName is the fully-qualified name of the GreetingService service.
	GreetingServiceName = "helloapp.v1.GreetingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GreetingServiceHelloProcedure is the fully-qualified name of the GreetingService's Hello RPC.
	GreetingServiceHelloProcedure = "/helloapp.v1.GreetingService/Hello"
)

// GreetingServiceClient is a client for the helloapp.v1.GreetingService service.
type GreetingServiceClient interface {
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
}

// NewGreetingServiceClient constructs a client for the helloapp.v1.GreetingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGreetingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GreetingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	greetingServiceMethods := v1.File_helloapp_v1_hello_proto.Services().ByName("GreetingService").Methods()
	return &greetingServiceClient{
		hello: connect.NewClient[v1.HelloRequest, v1.HelloResponse](
			httpClient,
			baseURL+GreetingServiceHelloProcedure,
			connect.WithSchema(greetingServiceMethods.ByName("Hello")),
			connect.WithClientOptions(opts...),
		),
	}
}

// greetingServiceClient implements GreetingServiceClient.
type greetingServiceClient struct {
	hello *connect.Client[v1.HelloRequest, v1.HelloResponse]
}

// Hello calls helloapp.v1.GreetingService.Hello.
func (c *greetingServiceClient) Hello(ctx context.Context, req *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// GreetingServiceHandler is an implementation of the helloapp.v1.GreetingService service.
type GreetingServiceHandler interface {
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
}

// NewGreetingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGreetingServiceHandler(svc GreetingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	greetingServiceMethods := v1.File_helloapp_v1_hello_proto.Services().ByName("GreetingService").Methods()
	greetingServiceHelloHandler := connect.NewUnaryHandler(
		GreetingServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(greetingServiceMethods.ByName("Hello")),
		connect.WithHandlerOptions(opts...),
	)
	return "/helloapp.v1.GreetingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GreetingServiceHelloProcedure:
			greetingServiceHelloHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGreetingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGreetingServiceHandler struct{}

func (UnimplementedGreetingServiceHandler) Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("helloapp.v1.GreetingService.Hello is not implemented"))
}
